### ISSUE TITLE
Branch / Tag?

### ISSUE THREAD

**Issue by dothebart** [inovex/tensorflow-lite-demo#1]
Hi, 
which branch or tag of https://github.com/tensorflow/models is meant to be chosen for the article at https://www.inovex.de/blog/deep-learning-mobile-tensorflow-lite/ ? It seems one either sees https://github.com/tensorflow/models/issues/1962 or with the latest release of them there object_detection/export_tflite_graph_tf2.py isn't there at all?

**Comment by RobinBaumann** [comment]
Hi, 
I tried to reproduce your error. However, when I clone the repository and `initialize` + `update` the `git submodule` I end up with commit `eef4e2dd9d2` being checked out from https://github.com/tensorflow/models, which contains the file and doesn't cause any issue with my installation.  The file `object_detection/export_tflite_graph_tf2.py` is even present on the master branch of the TF Object Detection API. 

Can you share some further information about your system? Scanning tensorflow/models#1962, it seems like this could be a problem on windows.

**Comment by dothebart** [comment]
Hi, 
its a debian buster chroot (tflite doesn't support python 3.9 on bullseye :/ ) 
I now did the submodule init - had put it next to that checkout. However, it doesn't change anything:
```
root@bithorizon:/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research# export PYTHONPATH=`pwd`:`pwd`/object_detection/protos
root@bithorizon:/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research# python3 object_detection/export_tflite_graph_tf2.py   --pipeline_config_path $PIPELINE_CONFIG_PATH   --trained_checkpoint_dir $MODEL_DIR   --output_directory tensorflow-lite-demo/model/ssd_mobilenet_v2/tflite
Traceback (most recent call last):
  File "object_detection/export_tflite_graph_tf2.py", line 80, in <module>
    from object_detection import export_tflite_graph_lib_tf2
  File "/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research/object_detection/export_tflite_graph_lib_tf2.py", line 22, in <module>
    from object_detection.builders import model_builder
  File "/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research/object_detection/builders/model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research/object_detection/builders/anchor_generator_builder.py", line 27, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' (/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research/object_detection/protos/__init__.py)
```
however:
```
root@bithorizon:/home/willi/src/tf/tensorflow-lite-demo# find |grep anchor_generator_pb2 
root@bithorizon:/home/willi/src/tf/tensorflow-lite-demo# grep -R anchor_generator_pb2 
od-api/models/research/object_detection/builders/anchor_generator_builder.py:from object_detection.protos import anchor_generator_pb2
od-api/models/research/object_detection/builders/anchor_generator_builder.py:                    anchor_generator_pb2.AnchorGenerator):
od-api/models/research/object_detection/builders/anchor_generator_builder.py:                     'anchor_generator_pb2.AnchorGenerator')
Binary file od-api/models/research/object_detection/builders/__pycache__/anchor_generator_builder.cpython-37.pyc matches
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:from object_detection.protos import anchor_generator_pb2
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
od-api/models/research/object_detection/builders/anchor_generator_builder_test.py:    anchor_generator_proto = anchor_generator_pb2.AnchorGenerator()
```
the git status here is:
```
root@bithorizon:/home/willi/src/tf/tensorflow-lite-demo/od-api/models/research# git status . 
HEAD detached at eef4e2dd
nothing to commit, working tree clean
```
moving it to the hash you provided doesn't change the error. 
running `python3 setup.py install` only changes the paths where the error is located: 
```
ImportError: cannot import name 'anchor_generator_pb2' from 'object_detection.protos' (/usr/local/lib/python3.7/dist-packages/object_detection-0.1-py3.7.egg/object_detection/protos/__init__.py)
```

**Comment by RobinBaumann** [comment]
Hmm, that seems to be an issue with the Object Detection API. Can you install it separately by following the instructions here:

https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/tf2.md

If not, I would suggest opening an issue in their repository.
